name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Automatic Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Comment PR
            uses: thollander/actions-comment-pull-request@v1
          with:
            message: 'Rebase message 123'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

